export function getInitialState() {
  return {
    activeTab: 'reports',
    searchTerm: '',
    modal: null,
    notifications: [],
    tutors: [
      {
        id: '1',
        name: 'María González',
        email: 'maria@email.com',
        phone: '+57 300 123 4567',
        address: 'Calle 45 #23-12',
        city: 'Bogotá',
        idNumber: '123456789',
      },
      {
        id: '2',
        name: 'Carlos Rodríguez',
        email: 'carlos@email.com',
        phone: '+57 310 987 6543',
        address: 'Carrera 15 #67-89',
        city: 'Medellín',
        idNumber: '987654321',
      },
    ],
    pets: [
      {
        id: '1',
        name: 'Max',
        species: 'Perro',
        breed: 'Labrador',
        age: 3,
        weight: 28.5,
        color: 'Dorado',
        gender: 'Macho',
        tutorId: '1',
      },
      {
        id: '2',
        name: 'Luna',
        species: 'Gato',
        breed: 'Siamés',
        age: 2,
        weight: 4.2,
        color: 'Blanco y Gris',
        gender: 'Hembra',
        tutorId: '1',
      },
      {
        id: '3',
        name: 'Rocky',
        species: 'Perro',
        breed: 'Bulldog',
        age: 4,
        weight: 22,
        color: 'Marrón',
        gender: 'Macho',
        tutorId: '2',
      },
    ],
    medicalRecords: [
      {
        id: '1',
        petId: '1',
        date: '2026-04-15',
        type: 'Vacunación',
        diagnosis: 'Aplicación de vacuna antirrábica anual',
        treatment: 'Vacuna antirrábica 1ml IM',
        observations: 'Paciente en buen estado de salud',
        nextVisit: '2027-04-15',
        weight: 28.5,
        temperature: 38.2,
        veterinarian: 'Dra. Ana Martínez',
      },
      {
        id: '2',
        petId: '2',
        date: '2026-03-10',
        type: 'Consulta General',
        diagnosis: 'Infección respiratoria leve',
        treatment: 'Amoxicilina 50mg cada 12h por 7 días',
        observations: 'Evitar corrientes de aire',
        nextVisit: '2026-03-24',
        weight: 4.2,
        temperature: 39.1,
        veterinarian: 'Dr. Carlos López',
      },
    ],
    appointments: [
      {
        id: '1',
        petId: '1',
        tutorId: '1',
        petName: 'Max',
        date: '2026-06-04',
        time: '09:30',
        reason: 'Control general',
        veterinarian: 'Dra. Ana Martínez',
        status: 'Confirmada',
      },
      {
        id: '2',
        petId: '2',
        tutorId: '1',
        petName: 'Luna',
        date: '2026-06-05',
        time: '11:00',
        reason: 'Vacunación',
        veterinarian: 'Dr. Carlos López',
        status: 'Pendiente',
      },
    ],
    inventory: [
      {
        id: '1',
        name: 'Vacuna antirrábica',
        category: 'Medicamentos',
        quantity: 18,
        price: 120000,
        status: 'Disponible',
      },
      {
        id: '2',
        name: 'Guantes de nitrilo',
        category: 'Insumos',
        quantity: 6,
        price: 28000,
        status: 'Stock bajo',
      },
      {
        id: '3',
        name: 'Shampoo antipulgas',
        category: 'Cuidado',
        quantity: 11,
        price: 46000,
        status: 'Disponible',
      },
    ],
  };
}

export const tabs = [
  { id: 'notifications', label: 'Notificaciones', icon: 'bell' },
  { id: 'patients', label: 'Gestión de Pacientes', icon: 'users' },
  { id: 'appointments', label: 'Agenda de Citas', icon: 'calendar' },
  { id: 'history', label: 'Historia Clínica', icon: 'file' },
  { id: 'inventory', label: 'Inventario', icon: 'box' },
  { id: 'reports', label: 'Reportes', icon: 'chart' },
];

export const tutorTabs = [
  { id: 'my-pets', label: 'Mis mascotas', icon: 'paw' },
  { id: 'my-history', label: 'Historial clínico', icon: 'file' },
  { id: 'request-appointment', label: 'Solicitar cita', icon: 'calendar-plus' },
  { id: 'notifications', label: 'Notificaciones', icon: 'bell' },
];

export const vetTabs = [
  { id: 'vet-appointments', label: 'Mis citas', icon: 'calendar' },
  { id: 'notifications', label: 'Notificaciones', icon: 'bell' },
];

export const authUsers = [
  {
    role: 'admin',
    email: 'admin@clinic.com',
    password: 'Veterinaria2026',
    displayName: 'Administrador',
  },
  {
    role: 'tutor',
    tutorId: '1',
    email: 'maria@email.com',
    password: 'Maria2026',
    displayName: 'María González',
  },
  {
    role: 'tutor',
    tutorId: '2',
    email: 'carlos@email.com',
    password: 'Carlos2026',
    displayName: 'Carlos Rodríguez',
  },
  {
    role: 'veterinarian',
    email: 'ana.martinez@clinic.com',
    password: 'Ana2026',
    displayName: 'Dra. Ana Martínez',
  },
  {
    role: 'veterinarian',
    email: 'carlos.lopez@clinic.com',
    password: 'CarlosVet2026',
    displayName: 'Dr. Carlos López',
  },
  {
    role: 'veterinarian',
    email: 'laura.torres@clinic.com',
    password: 'Laura2026',
    displayName: 'Dra. Laura Torres',
  },
  {
    role: 'veterinarian',
    email: 'felipe.rojas@clinic.com',
    password: 'Felipe2026',
    displayName: 'Dr. Felipe Rojas',
  },
  {
    role: 'veterinarian',
    email: 'sofia.herrera@clinic.com',
    password: 'Sofia2026',
    displayName: 'Dra. Sofía Herrera',
  },
];
